# Generated by Django 2.1 on 2019-12-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('processed_text', models.TextField(default='')),
                ('result_1', models.TextField(default='')),
                ('result_2', models.TextField(default='')),
                ('result_3', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CompareItemJD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('result_1', models.TextField(default='')),
                ('result_2', models.TextField(default='')),
                ('result_3', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CompareItemJT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('result_1', models.TextField(default='')),
                ('result_2', models.TextField(default='')),
                ('result_3', models.TextField(default='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='compareitemjt',
            unique_together={('content', 'result_1', 'result_2', 'result_3')},
        ),
        migrations.AlterUniqueTogether(
            name='compareitemjd',
            unique_together={('content', 'result_1', 'result_2', 'result_3')},
        ),
        migrations.AlterUniqueTogether(
            name='compareitem',
            unique_together={('title', 'description', 'processed_text', 'result_1', 'result_2', 'result_3')},
        ),
    ]
